defaults:
  - _self_
  - data: capture24_10s
  - evaluation: all
  - model: resnet
  - dataloader: ten_sec

gpu: -1
gpu_ids: [0, 1, 2]  # gpus to use if multi_gpu==true
multi_gpu: false
num_split: 5
augmentation: true
model_path: /Users/theb/Documents/PhD/code/ssl-wearables/model_check_point/mtl_best.mdl
logging_path: /data/UKBB/SSL/evaluations
report_root: "/home/cxx579/ssw/reports/"
output_path: '/Users/theb/Documents/PhD/code/ssl-wearables/outputs/'
# report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}.csv"
report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}_${evaluation.subR}.csv"
is_verbose: false
